site_name: Rago Meditation App
site_url: https://bytefield.github.io/rago_enterprises/
repo_url: https://github.com/Bytefield/rago_enterprises
repo_name: Bytefield/rago_enterprises

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - redirects:
      redirect_maps:
        'index.md': 'Home.md'

nav:
  - Home: 'Home.md'
  - Getting Started:
    - 'Getting Started/Installation.md'
    - 'Getting Started/Configuration.md'
    - 'Getting Started/Development-Setup.md'
  - API Documentation:
    - 'API/Authentication.md'
    - 'API/Meditation-Sessions.md'
    - 'API/Users.md'
  - Architecture:
    - 'Architecture/Overview.md'
  - Development:
    - 'Development/Guide.md'
  - Contributing:
    - 'Contributing/How-to-Contribute.md'
    - 'Contributing/Pull-Request-Process.md'
    - 'Contributing/Code-Review-Guidelines.md'
